Call ( "Common.Init" );
CloseAll ();

fill ( "NBMDMD2X", """Banca Nationala a Moldovei"" Chisinau" );
fill ( "BIIDMD2X", """BIID MB"" S.A. Chisinau" );
fill ( "FTMDMD2X", """Fincombank"" S.A. Chisinau" );
fill ( "FTMDMD2X735", """Fincombank"" S.A. filiala nr. 1 Chisinau" );
fill ( "FTMDMD2X401", """Fincombank"" S.A. filiala nr. 10 Floresti" );
fill ( "FTMDMD2X891", """Fincombank"" S.A. filiala nr. 11 Ungheni" );
fill ( "FTMDMD2X411", """Fincombank"" S.A. filiala nr. 12 Comrat" );
fill ( "FTMDMD2X423", """Fincombank"" S.A. filiala nr. 15 Edinet" );
fill ( "FTMDMD2X847", """Fincombank"" S.A. filiala nr. 2 Chisinau" );
fill ( "FTMDMD2X853", """Fincombank"" S.A. filiala nr. 3 Chisinau" );
fill ( "FTMDMD2X848", """Fincombank"" S.A. filiala nr. 4 Balti" );
fill ( "FTMDMD2X471", """Fincombank"" S.A. filiala nr. 4 Hincesti" );
fill ( "FTMDMD2X874", """Fincombank"" S.A. filiala nr. 5 Orhei" );
fill ( "FTMDMD2X873", """Fincombank"" S.A. filiala nr. 6 Chisinau" );
fill ( "FTMDMD2X889", """Fincombank"" S.A. filiala nr. 7 Chisinau" );
fill ( "FTMDMD2X886", """Fincombank"" S.A. filiala nr. 8 Cahul" );
fill ( "FTMDMD2X890", """Fincombank"" S.A. filiala nr. 9 Riscani" );
fill ( "NBMDMD2XIPS", "AIPS (Sistemul de Plati)" );
fill ( "NBMDMD2XBPL", "Balanta de Plati" );
fill ( "GUINMD2X", "Banca ""GUINEA"" S.A. Chisinau" );
fill ( "RNCBMD2X454", "Banca Comerciala Romana  S.A. filiala nr. 1 Balti" );
fill ( "RNCBMD2X", "Banca Comerciala Romana S.A.Chisinau" );
fill ( "NORDMD2X", "Banca municipala ""Chisinau"" S.A." );
fill ( "NORDMD2X849", "Banca municipala ""Chisinau"" S.A. filiala nr. 1 Balti" );
fill ( "BMUNMD2X", "Banca Municipala S.A. Chisinau" );
fill ( "BMUNMD2X849", "Banca Municipala S.A. filiala nr. 1 Balti" );
fill ( "SINDMD2X", "BC ""Bancosind"" S.A. Chisinau" );
fill ( "BASBMD2X", "BC ""Basarabia"" Chisinau" );
fill ( "BTRBMD2X", "BC ""BTR Moldova"" S.A. Chisinau" );
fill ( "BUCBMD2X", "BC ""Bucuriabanc"" S.A. Chisinau" );
fill ( "BUSEMD22", "BC ""Businessbank"" S.A. Chisinau" );
fill ( "BUSEMD22888", "BC ""Businessbank"" S.A. filiala nr. 1 Balti" );
fill ( "CAPBMD2X", "BC ""Capital-Bank"" S.A. Chisinau" );
fill ( "CMTBMD2X", "BC ""Comertbank"" S.A. Chisinau" );
fill ( "ENEGMD22", "BC ""Energbank"" S.A. Chisinau" );
fill ( "ENEGMD22858", "BC ""Energbank"" S.A. filiala ""Botanica"" Chisinau" );
fill ( "ENEGMD22893", "BC ""Energbank"" S.A. filiala ""Buiucani"" Chisinau" );
fill ( "ENEGMD22895", "BC ""Energbank"" S.A. filiala ""Centru"" Chisinau" );
fill ( "ENEGMD22408", "BC ""Energbank"" S.A. filiala ""Ciocana Noua"" Chisinau" );
fill ( "ENEGMD22409", "BC ""Energbank"" S.A. filiala ""Ismail"" Chisinau" );
fill ( "ENEGMD22407", "BC ""Energbank"" S.A. filiala ""Riscani"" Chisinau" );
fill ( "ENEGMD22505", "BC ""ENERGBANK"" S.A. Filiala Anenii Noi" );
fill ( "ENEGMD22402", "BC ""Energbank"" S.A. filiala Balti" );
fill ( "ENEGMD22425", "BC ""Energbank"" S.A. filiala Briceni" );
fill ( "ENEGMD22405", "BC ""Energbank"" S.A. filiala Cahul" );
fill ( "ENEGMD22896", "BC ""Energbank"" S.A. filiala Comrat" );
fill ( "ENEGMD22484", "BC ""Energbank"" S.A. filiala Cricova" );
fill ( "ENEGMD22406", "BC ""Energbank"" S.A. filiala Criuleni" );
fill ( "ENEGMD22506", "BC ""Energbank"" S.A. filiala Donduşeni" );
fill ( "ENEGMD22898", "BC ""Energbank"" S.A. filiala Drochia" );
fill ( "ENEGMD22894", "BC ""Energbank"" S.A. filiala Edinet" );
fill ( "ENEGMD22448", "BC ""Energbank"" S.A. filiala Floresti" );
fill ( "ENEGMD22412", "BC ""Energbank"" S.A. filiala Hincesti" );
fill ( "ENEGMD22410", "BC ""Energbank"" S.A. filiala Leova" );
fill ( "ENEGMD22403", "BC ""Energbank"" S.A. filiala Ocnita" );
fill ( "ENEGMD22897", "BC ""Energbank"" S.A. filiala Orhei" );
fill ( "ENEGMD22899", "BC ""Energbank"" S.A. filiala Soroca" );
fill ( "ENEGMD22487", "BC ""Energbank"" S.A. filiala Taraclia" );
fill ( "ECBMMD2X757", "BC ""EuroCreditBank"" S.A. Balti" );
fill ( "ECBMMD2X501", "BC ""EuroCreditBank"" S.A. Cahul" );
fill ( "ECBMMD2X", "BC ""EuroCreditBank"" S.A. Chisinau" );
fill ( "ECBMMD2X499", "BC ""EuroCreditBank"" S.A. Orhei" );
fill ( "ECBMMD2X812", "BC ""EuroCreditBank"" S.A. Ungheni" );
fill ( "EXMMMD22", "BC ""Eximbank"" S.A. Gruppo Veneto Banca Chisinau" );
fill ( "EXMMMD22831", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 1 Comrat" );
fill ( "EXMMMD22429", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 10 Chisinau" );
fill ( "EXMMMD22436", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 11 Chisinau" );
fill ( "EXMMMD22430", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 12 Chisinau" );
fill ( "EXMMMD22426", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 13 Chisinau" );
fill ( "EXMMMD22431", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 14 Chisinau" );
fill ( "EXMMMD22450", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 15 Cahul" );
fill ( "EXMMMD22470", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 16 Hincesti" );
fill ( "EXMMMD22440", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 17 Chisinau" );
fill ( "EXMMMD22427", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 18 Balti" );
fill ( "EXMMMD22476", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 19 Chisinau" );
fill ( "EXMMMD22835", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 2 Ungheni" );
fill ( "EXMMMD22477", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 20 Chisinau" );
fill ( "EXMMMD22495", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 22 Chisinau" );
fill ( "EXMMMD22496", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 23 Chisinau" );
fill ( "EXMMMD22404", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 3 Chisinau" );
fill ( "EXMMMD22417", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 4 Causeni" );
fill ( "EXMMMD22418", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 5 Orhei" );
fill ( "EXMMMD22419", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 6 Chisinau" );
fill ( "EXMMMD22420", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 7 Chisinau" );
fill ( "EXMMMD22414", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 8 Soroca" );
fill ( "EXMMMD22422", "BC ""Eximbank"" S.A. Gruppo Veneto Banca filiala nr. 9 Chisinau" );
fill ( "IPRZMD2X", "BC ""Intreprinzbanca"" S.A. Chisinau" );
fill ( "INVVMD22", "BC ""InvestPrivatBank"" S.A. Chisinau" );
fill ( "MOBBMD22", "BC ""Mobiasbanca - Groupe Societe Generale"" S.A. Chisinau" );
fill ( "MOBBMD22880", "BC ""Mobiasbanca - Groupe Societe Generale"" S.A. filiala nr. 1 ""Stejaur"" Chisinau" );
fill ( "MOBBMD22421", "BC ""Mobiasbanca - Groupe Societe Generale"" S.A. filiala nr. 10 ""Cahul""" );
fill ( "MOBBMD22424", "BC ""Mobiasbanca - Groupe Societe Generale"" S.A. filiala nr. 11 ""Balti""" );
fill ( "MOBBMD22432", "BC ""Mobiasbanca - Groupe Societe Generale"" S.A. filiala nr. 12 ""Edinet""" );
fill ( "MOBBMD22439", "BC ""Mobiasbanca - Groupe Societe Generale"" S.A. filiala nr. 13 ""Orhei""" );
fill ( "MOBBMD22453", "BC ""Mobiasbanca - Groupe Societe Generale"" S.A. filiala nr. 14 ""Comrat""" );
fill ( "MOBBMD22881", "BC ""Mobiasbanca - Groupe Societe Generale"" S.A. filiala nr. 2 ""ICAM"" Chisinau" );
fill ( "MOBBMD22811", "BC ""Mobiasbanca - Groupe Societe Generale"" S.A. filiala nr. 3 ""Ciocana""" );
fill ( "MOBBMD22816", "BC ""Mobiasbanca - Groupe Societe Generale"" S.A. filiala nr. 4 ""Dacia""" );

fill ( "MOBBMD22809", "BC ""Mobiasbanca - Groupe Societe Generale"" S.A. filiala nr. 5 ""Riscani""" );
fill ( "MOBBMD22730", "BC ""Mobiasbanca - Groupe Societe Generale"" S.A. filiala nr. 6 ""Aneni""" );
fill ( "MOBBMD22879", "BC ""Mobiasbanca - Groupe Societe Generale"" S.A. filiala nr. 7 ""Renastere"" Chisinau" );
fill ( "MOBBMD22875", "BC ""Mobiasbanca - Groupe Societe Generale"" S.A. filiala nr. 8 ""Ungheni""" );
fill ( "MOBBMD22749", "BC ""Mobiasbanca - Groupe Societe Generale"" S.A. filiala nr. 9 ""Centru"" Chisinau" );
fill ( "MOLDMD2X", "BC ""MOLDINDCONBANK"" S.A. Chisinau" );
fill ( "MOLDMD2X357", "BC ""Moldindconbank"" S.A. filiala ,,Durleşti""" );
fill ( "MOLDMD2X349", "BC ""Moldindconbank"" S.A. filiala 'Ciocana' Chisinau" );
fill ( "MOLDMD2X309", "BC ""Moldindconbank"" S.A. filiala ""Centru"" Chisinau" );
fill ( "MOLDMD2X329", "BC ""Moldindconbank"" S.A. filiala ""Invest"" Chisinau" );
fill ( "MOLDMD2X336", "BC ""Moldindconbank"" S.A. filiala ""Kiev"" Chisinau" );
fill ( "MOLDMD2X319", "BC ""Moldindconbank"" S.A. filiala ""Onest"" Chisinau" );
fill ( "MOLDMD2X317", "BC ""Moldindconbank"" S.A. filiala ""Remiz"" Chisinau" );
fill ( "MOLDMD2X300", "BC ""Moldindconbank"" S.A. filiala ""STABIL"" Chisinau" );
fill ( "MOLDMD2X334", "BC ""Moldindconbank"" S.A. filiala ""Ştefan cel Mare"" Chisinau" );
fill ( "MOLDMD2X332", "BC ""Moldindconbank"" S.A. filiala ""Telecomtrans""" );
fill ( "MOLDMD2Х330", "BC ""Moldindconbank"" S.A. filiala ""Zorile"" Chisinau" );
fill ( "MOLDMD2X313", "BC ""Moldindconbank"" S.A. filiala “Flacara” Chisinau" );
fill ( "MOLDMD2Х366", "BC ""Moldindconbank"" S.A. filiala „ALECU RUSSO” Chisinau" );
fill ( "MOLDMD2X361", "BC ""Moldindconbank"" S.A. filiala „Armenească” Chisinau" );
fill ( "MOLDMD2Х328", "BC ""Moldindconbank"" S.A. filiala „Burebista”Chisinau" );
fill ( "MOLDMD2X308", "BC ""Moldindconbank"" S.A. filiala „Dacia” Chisinau" );
fill ( "MOLDMD2Х363", "BC ""Moldindconbank"" S.A. filiala „DECEBAL” Chisinau" );
fill ( "MOLDMD2X359", "BC ""Moldindconbank"" S.A. filiala „Mircea cel Bătrîn” Chisinau" );
fill ( "MOLDMD2Х364", "BC ""Moldindconbank"" S.A. filiala „Moscova” Chisinau" );
fill ( "MOLDMD2Х358", "BC ""Moldindconbank"" S.A. filiala „Paris”Chisinau" );
fill ( "MOLDMD2X307", "BC ""Moldindconbank"" S.A. filiala „Poşta Veche” Chisinau" );
fill ( "MOLDMD2X320", "BC ""Moldindconbank"" S.A. filiala „Premium” Chisinau" );
fill ( "MOLDMD2X312", "BC ""Moldindconbank"" S.A. filiala „Renaştere” Chisinau" );
fill ( "MOLDMD2X306", "BC ""Moldindconbank"" S.A. filiala „Telecentru” Chisinau" );
fill ( "MOLDMD2Х365", "BC ""Moldindconbank"" S.A. filiala „TUDOR VLADIMIRESCU” Chisinau" );
fill ( "MOLDMD2Х367", "BC ""Moldindconbank"" S.A. filiala „VASILE ALECSANDRI” Chisinau" );
fill ( "MOLDMD2Х338", "BC ""Moldindconbank"" S.A. filiala Anenii Noi" );
fill ( "MOLDMD2X321", "BC ""Moldindconbank"" S.A. filiala Balti" );
fill ( "MOLDMD2X342", "BC ""Moldindconbank"" S.A. filiala Briceni" );
fill ( "MOLDMD2X348", "BC ""Moldindconbank"" S.A. filiala Cahul" );
fill ( "MOLDMD2Х353", "BC ""Moldindconbank"" S.A. filiala Calarasi" );
fill ( "MOLDMD2X344", "BC ""Moldindconbank"" S.A. filiala Causeni" );
fill ( "MOLDMD2Х343", "BC ""Moldindconbank"" S.A. filiala Ciadir Lunga" );
fill ( "MOLDMD2X315", "BC ""Moldindconbank"" S.A. filiala Cimislia" );
fill ( "MOLDMD2X350", "BC ""Moldindconbank"" S.A. filiala Comrat" );
fill ( "MOLDMD2Х340", "BC ""Moldindconbank"" S.A. filiala Criuleni" );
fill ( "MOLDMD2X327", "BC ""Moldindconbank"" S.A. filiala Donduseni" );
fill ( "MOLDMD2X316", "BC ""Moldindconbank"" S.A. filiala Drochia" );
fill ( "MOLDMD2X326", "BC ""Moldindconbank"" S.A. filiala Edinet" );
fill ( "MOLDMD2Х351", "BC ""Moldindconbank"" S.A. filiala Falesti" );
fill ( "MOLDMD2X341", "BC ""Moldindconbank"" S.A. filiala Floresti" );
fill ( "MOLDMD2X322", "BC ""Moldindconbank"" S.A. filiala Giurgiulesti" );
fill ( "MOLDMD2Х352", "BC ""Moldindconbank"" S.A. filiala Glodeni" );
fill ( "MOLDMD2X323", "BC ""Moldindconbank"" S.A. filiala Hincesti" );
fill ( "MOLDMD2X314", "BC ""Moldindconbank"" S.A. filiala Ialoveni" );
fill ( "MOLDMD2X318", "BC ""Moldindconbank"" S.A. filiala Leova" );
fill ( "MOLDMD2Х345", "BC ""Moldindconbank"" S.A. filiala Nisporeni" );
fill ( "MOLDMD2X303", "BC ""Moldindconbank"" S.A. filiala nr. 15 Chisinau" );
fill ( "MOLDMD2X304", "BC ""Moldindconbank"" S.A. filiala nr. 16 Vatra" );
fill ( "MOLDMD2X305", "BC ""Moldindconbank"" S.A. filiala nr. 18 Durlesti" );
fill ( "MOLDMD2X301", "BC ""Moldindconbank"" S.A. filiala nr. 2 Chisinau" );
fill ( "MOLDMD2X302", "BC ""Moldindconbank"" S.A. filiala nr. 8 Chisinau" );
fill ( "MOLDMD2X360", "BC ""Moldindconbank"" S.A. filiala Ocnita" );
fill ( "MOLDMD2X333", "BC ""Moldindconbank"" S.A. filiala Orhei" );
fill ( "MOLDMD2X335", "BC ""Moldindconbank"" S.A. filiala Rezina" );
fill ( "MOLDMD2Х354", "BC ""Moldindconbank"" S.A. filiala Riscani" );
fill ( "MOLDMD2Х339", "BC ""Moldindconbank"" S.A. filiala Singerei" );
fill ( "MOLDMD2Х355", "BC ""Moldindconbank"" S.A. filiala Soldanesti" );
fill ( "MOLDMD2X337", "BC ""Moldindconbank"" S.A. filiala Soroca" );
fill ( "MOLDMD2X324", "BC ""Moldindconbank"" S.A. filiala Strasani" );
fill ( "MOLDMD2X347", "BC ""Moldindconbank"" S.A. filiala Taraclia" );
fill ( "MOLDMD2Х356", "BC ""Moldindconbank"" S.A. filiala Telenesti" );
fill ( "MOLDMD2X346", "BC ""Moldindconbank"" S.A. filiala Ungheni" );
fill ( "MOLDMD2X362", "BC ""Moldindconbank"" S.A. filiala Vulcanesti" );
fill ( "AGRNMD2X", "BC ""Moldova-Agroindbank"" S.A. Chisinau" );
fill ( "AGRNMD2X832", "BC ""Moldova-Agroindbank"" S.A. filiala ""Chisinau-Buiucani"" Chisinau" );
fill ( "AGRNMD2X723", "BC ""Moldova-Agroindbank"" S.A. filiala ""Chisinau-Centru"" Chisinau" );
fill ( "AGRNMD2X864", "BC ""Moldova-Agroindbank"" S.A. filiala ""M.Eminescu"" Chisinau" );
fill ( "AGRNMD2X437", "BC ""Moldova-Agroindbank"" S.A. filiala 10 Chisinau" );
fill ( "AGRNMD2X433", "BC ""Moldova-Agroindbank"" S.A. filiala 11 Chisinau" );
fill ( "AGRNMD2X438", "BC ""Moldova-Agroindbank"" S.A. filiala 12 Chisinau" );
fill ( "AGRNMD2X442", "BC ""Moldova-Agroindbank"" S.A. filiala 14 Chisinau" );
fill ( "AGRNMD2X443", "BC ""Moldova-Agroindbank"" S.A. filiala 15 Chisinau" );
fill ( "AGRNMD2X451", "BC ""Moldova-Agroindbank"" S.A. filiala 16 Chisinau" );
fill ( "AGRNMD2X444", "BC ""Moldova-Agroindbank"" S.A. filiala 17 Chisinau" );
fill ( "AGRNMD2X441", "BC ""Moldova-Agroindbank"" S.A. filiala 18 Chisinau" );
fill ( "AGRNMD2X456", "BC ""Moldova-Agroindbank"" S.A. filiala 19 Chisinau" );
fill ( "AGRNMD2X452", "BC ""Moldova-Agroindbank"" S.A. filiala 20 Chisinau" );
fill ( "AGRNMD2X445", "BC ""Moldova-Agroindbank"" S.A. filiala 21 Chisinau" );
fill ( "AGRNMD2X467", "BC ""Moldova-Agroindbank"" S.A. filiala 22 Chisinau" );
fill ( "AGRNMD2X458", "BC ""Moldova-Agroindbank"" S.A. filiala 23 Chisinau" );
fill ( "AGRNMD2X472", "BC ""Moldova-Agroindbank"" S.A. filiala 25 Chisinau" );
fill ( "AGRNMD2X462", "BC ""Moldova-Agroindbank"" S.A. filiala 26 Chisinau" );
fill ( "AGRNMD2X435", "BC ""Moldova-Agroindbank"" S.A. filiala 5 Chisinau" );
fill ( "AGRNMD2X413", "BC ""Moldova-Agroindbank"" S.A. filiala 6 Chisinau" );
fill ( "AGRNMD2X415", "BC ""Moldova-Agroindbank"" S.A. filiala 7 Chisinau" );
fill ( "AGRNMD2X455", "BC ""Moldova-Agroindbank"" S.A. filiala 8 Chisinau" );
fill ( "AGRNMD2X434", "BC ""Moldova-Agroindbank"" S.A. filiala 9 Chisinau" );
fill ( "AGRNMD2X796", "BC ""Moldova-Agroindbank"" S.A. filiala Anenii Noi" );
fill ( "AGRNMD2X750", "BC ""Moldova-Agroindbank"" S.A. filiala Balti" );
fill ( "AGRNMD2X786", "BC ""Moldova-Agroindbank"" S.A. filiala Basarabeas" );
fill ( "AGRNMD2X763", "BC ""Moldova-Agroindbank"" S.A. filiala Briceni" );
fill ( "AGRNMD2X756", "BC ""Moldova-Agroindbank"" S.A. filiala Cahul" );
fill ( "AGRNMD2X768", "BC ""Moldova-Agroindbank"" S.A. filiala Calarasi" );
fill ( "AGRNMD2X712", "BC ""Moldova-Agroindbank"" S.A. filiala Cantemir" );
fill ( "AGRNMD2X461", "BC ""Moldova-Agroindbank"" S.A. filiala Carpineni" );
fill ( "AGRNMD2X769", "BC ""Moldova-Agroindbank"" S.A. filiala Causeni" );
fill ( "AGRNMD2X781", "BC ""Moldova-Agroindbank"" S.A. filiala Ceadir-Lunga" );
fill ( "AGRNMD2X782", "BC ""Moldova-Agroindbank"" S.A. filiala Cimislia" );
fill ( "AGRNMD2X738", "BC ""Moldova-Agroindbank"" S.A. filiala Cocieri" );
fill ( "AGRNMD2X761", "BC ""Moldova-Agroindbank"" S.A. filiala Comrat" );
fill ( "AGRNMD2X474", "BC ""Moldova-Agroindbank"" S.A. filiala Copceac" );
fill ( "AGRNMD2X760", "BC ""Moldova-Agroindbank"" S.A. filiala Criuleni" );
fill ( "AGRNMD2X754", "BC ""Moldova-Agroindbank"" S.A. filiala Donduseni" );
fill ( "AGRNMD2X702", "BC ""Moldova-Agroindbank"" S.A. filiala Drochia" );
fill ( "AGRNMD2X791", "BC ""Moldova-Agroindbank"" S.A. filiala Edinet" );
fill ( "AGRNMD2X789", "BC ""Moldova-Agroindbank"" S.A. filiala Falesti" );
fill ( "AGRNMD2X780", "BC ""Moldova-Agroindbank"" S.A. filiala Floresti" );
fill ( "AGRNMD2X753", "BC ""Moldova-Agroindbank"" S.A. filiala Glodeni" );
fill ( "AGRNMD2X752", "BC ""Moldova-Agroindbank"" S.A. filiala Hincesti" );
fill ( "AGRNMD2X797", "BC ""Moldova-Agroindbank"" S.A. filiala Ialoveni" );
fill ( "AGRNMD2X764", "BC ""Moldova-Agroindbank"" S.A. filiala Leova" );
fill ( "AGRNMD2X466", "BC ""Moldova-Agroindbank"" S.A. filiala Lipcani" );
fill ( "AGRNMD2X710", "BC ""Moldova-Agroindbank"" S.A. filiala M.Costin Chisinau" );
fill ( "AGRNMD2X765", "BC ""Moldova-Agroindbank"" S.A. filiala Nisporeni" );
fill ( "AGRNMD2X885", "BC ""Moldova-Agroindbank"" S.A. filiala nr. 1 Chisinau" );
fill ( "AGRNMD2X876", "BC ""Moldova-Agroindbank"" S.A. filiala nr. 2 Chisinau" );
fill ( "AGRNMD2X877", "BC ""Moldova-Agroindbank"" S.A. filiala nr. 3 Chisinau" );
fill ( "AGRNMD2X887", "BC ""Moldova-Agroindbank"" S.A. filiala nr. 4 Chisinau" );
fill ( "AGRNMD2X792", "BC ""Moldova-Agroindbank"" S.A. filiala Ocnita" );
fill ( "AGRNMD2X766", "BC ""Moldova-Agroindbank"" S.A. filiala Orhei" );
fill ( "AGRNMD2X777", "BC ""Moldova-Agroindbank"" S.A. filiala Rezina" );
fill ( "AGRNMD2X779", "BC ""Moldova-Agroindbank"" S.A. filiala Riscani" );
fill ( "AGRNMD2X773", "BC ""Moldova-Agroindbank"" S.A. filiala Singerei" );
fill ( "AGRNMD2X707", "BC ""Moldova-Agroindbank"" S.A. filiala Soldanesti" );
fill ( "AGRNMD2X771", "BC ""Moldova-Agroindbank"" S.A. filiala Soroca" );
fill ( "AGRNMD2X762", "BC ""Moldova-Agroindbank"" S.A. filiala Stefan-Voda" );
fill ( "AGRNMD2X772", "BC ""Moldova-Agroindbank"" S.A. filiala Strasani" );
fill ( "AGRNMD2X774", "BC ""Moldova-Agroindbank"" S.A. filiala Taraclia" );
fill ( "AGRNMD2X775", "BC ""Moldova-Agroindbank"" S.A. filiala Telenesti" );
fill ( "AGRNMD2X788", "BC ""Moldova-Agroindbank"" S.A. filiala Ungheni" );
fill ( "AGRNMD2X795", "BC ""Moldova-Agroindbank"" S.A. filiala Vulcanesti" );
fill ( "PRCBMD22", "BC ""ProCredit Bank"" S.A. Chisinau" );
fill ( "VICBMD2X", "BC ""Victoriabank"" S.A. Chisinau" );
fill ( "VICBMD2X740", "BC ""Victoriabank"" S.A. filiala nr. 1 Balti" );
fill ( "VICBMD2X882", "BC ""Victoriabank"" S.A. filiala nr. 10 Ungheni" );
fill ( "VICBMD2X883", "BC ""Victoriabank"" S.A. filiala nr. 11 Chisinau" );
fill ( "VICBMD2X884", "BC ""Victoriabank"" S.A. filiala nr. 12 Chisinau" );
fill ( "VICBMD2X428", "BC ""Victoriabank"" S.A. filiala nr. 13 Taraclia" );
fill ( "VICBMD2X446", "BC ""Victoriabank"" S.A. filiala nr. 14 Chisinau" );
fill ( "VICBMD2X449", "BC ""Victoriabank"" S.A. filiala nr. 15 Comrat" );
fill ( "VICBMD2X447", "BC ""Victoriabank"" S.A. filiala nr. 16 Edinet" );
fill ( "VICBMD2X457", "BC ""Victoriabank"" S.A. filiala nr. 17 Chisinau" );
fill ( "VICBMD2X491", "BC ""Victoriabank"" S.A. filiala nr. 18 Hincesti" );
fill ( "VICBMD2X480", "BC ""Victoriabank"" S.A. filiala nr. 19 Briceni" );
fill ( "VICBMD2X709", "BC ""Victoriabank"" S.A. filiala nr. 2 Floresti" );
fill ( "VICBMD2X463", "BC ""Victoriabank"" S.A. filiala nr. 20 Chisinau" );
fill ( "VICBMD2X465", "BC ""Victoriabank"" S.A. filiala nr. 22 Ocnita" );
fill ( "VICBMD2X473", "BC ""Victoriabank"" S.A. filiala nr. 23 Straseni" );
fill ( "VICBMD2X479", "BC ""Victoriabank"" S.A. filiala nr. 24 Ialoveni" );
fill ( "VICBMD2X468", "BC ""Victoriabank"" S.A. filiala nr. 25 Singerei" );
fill ( "VICBMD2X469", "BC ""Victoriabank"" S.A. filiala nr. 26 Chisinau" );
fill ( "VICBMD2X507", "BC ""Victoriabank"" S.A. filiala nr. 27 Falesti" );
fill ( "VICBMD2X492", "BC ""Victoriabank"" S.A. filiala nr. 28 Calarasi" );
fill ( "VICBMD2X490", "BC ""Victoriabank"" S.A. filiala nr. 29 CChisinau" );
fill ( "VICBMD2X416", "BC ""Victoriabank"" S.A. filiala nr. 3 Chisinau" );
fill ( "VICBMD2X500", "BC ""Victoriabank"" S.A. filiala nr. 30 Chisinau" );
fill ( "VICBMD2X502", "BC ""Victoriabank"" S.A. filiala nr. 31 Drochia" );
fill ( "VICBMD2X503", "BC ""Victoriabank"" S.A. filiala nr. 32 Ceadir Lunga" );
fill ( "VICBMD2X806", "BC ""Victoriabank"" S.A. filiala nr. 4 Nisporeni" );
fill ( "VICBMD2X807", "BC ""Victoriabank"" S.A. filiala nr. 5 Causeni" );
fill ( "VICBMD2X808", "BC ""Victoriabank"" S.A. filiala nr. 6 Soroca" );
fill ( "VICBMD2X836", "BC ""Victoriabank"" S.A. filiala nr. 7 Orhei" );
fill ( "VICBMD2X802", "BC ""Victoriabank"" S.A. filiala nr. 8 Chisinau" );
fill ( "VICBMD2X871", "BC ""Victoriabank"" S.A. filiala nr. 9 Cahul" );
fill ( "OGUZMD2X", "BCI ""Oguzbank"" S.A. Comrat" );
fill ( "VIASMD2X", "BCIA ""Vias"" Chisinau" );
fill ( "NBMDMD2XLED", "Cartea Mare a BNM" );
fill ( "TIRCMD2X", "Centrul de casa si decontari Tiraspol" );
fill ( "NBMDMD2XDOP", "Departamentul Operatiuni de Piata" );
fill ( "NBMDMD2XDPM", "Departamentul Politica Monetara" );
fill ( "NBMDMD2XDSP", "Departamentul Sistemul de Plati" );
fill ( "OGUZMD2X842", "Filiala ""Basarabeasca-Oguzbank"" Basarabeasca" );
fill ( "OGUZMD2X844", "Filiala ""Cahul-Oguzbank"" Cahul" );
fill ( "OGUZMD2X843", "Filiala ""Chisinau-Oguzbank"" Chisinau" );
fill ( "OGUZMD2X839", "Filiala ""Ciadir-Oguzbank"" Ciadir-Lunga" );
fill ( "OGUZMD2X841", "Filiala ""Congaz-Oguzbank"" Congaz" );
fill ( "OGUZMD2X840", "Filiala ""Valcanes-Oguzbank"" Vulcanesti" );
fill ( "OGUZMD2X838", "Filiala generala ""Comrat-Oguzbank"" Comrat" );
fill ( "FGARMD2X101", "Fondul de Garantare a depozitelor in SB" );
fill ( "TREZMD2X", "Ministerul Finantelor Trezoreria de Stat" );
fill ( "280101000", "Organizatia nu are cont an banca" );
fill ( "NBMDMD2XSIC", "SIC (Sistemul Inscrieri in Conturi)" );
fill ( "NBMDMD2XBOS", "Sistemul BOSS" );
fill ( "NBMDMD2XSMI", "SMI (Sistemul Mesagelor Interbancare)" );
fill ( "NBMDMD2XSTO", "Statistica" );
fill ( "NBMDMD2XVAL", "Valuta" );

Procedure fill ( Code, Description )

	p = Call ( "Catalogs.BanksClassifier.Create.Params" );
	p.Code = Code;
	p.Description = Description;
	Call ( "Catalogs.BanksClassifier.Create", p );

EndProcedure

